### ISSUE TITLE
Use of file paths in configuration files

### ISSUE THREAD

**Issue by valbucci** [extensionsec/xcavate#3]
https://github.com/extensionsec/xcavate/blame/247f776220f2ed41f64f48174c349b6d7f59d13b/conf/scraper_configuration.yaml#L62

I am referring to this line of code to explain how I dealt with paths in the xcavate repository. There is a file in the xcavate.common module which is called context.py. This provides absolute paths to the system about where the repository root is located (this is called `PROJECT_ROOT`). 

When specifying file paths in the configuration files, assume that the program will look at it from the project's root (i.e. where the `ReadMe.md` file is located).

Therefore, the field `datafile: '../../data/ext_info_all.txt'` should be changed to `datafile: 'data/ext_info_all.txt'`. Make sure that your code makes use of the context module to accommodate this.

**Comment by Yang-Nankai** [comment]
OK, I got it!
