### ISSUE TITLE
Variable naming and function documentation

### ISSUE THREAD

**Issue by valbucci** [extensionsec/xcavate#4]
https://github.com/extensionsec/xcavate/blob/247f776220f2ed41f64f48174c349b6d7f59d13b/xcavate/data_spider/common.py#L16

Try to give meaningful names to your variables. When I read "stri" I don't know what this variable is supposed to be except from having a string format. However, there is already the function `int()` that can convert a string to an integer, so it's obvious that this variable should have some specific characteristics. 

You didn't write any documentation for this function and the name is not self-explanatory (why are we using this function instead of `int()`?). I'm sure there is a better naming that can be adopted here and in the rest of the files.

**Comment by valbucci** [comment]
https://github.com/extensionsec/xcavate/blob/247f776220f2ed41f64f48174c349b6d7f59d13b/xcavate/data_spider/common.py#L21

What data? How is this data stored in the dictionary? What is the key and what is the value? You should include all these information in your documentation

**Comment by valbucci** [comment]
https://github.com/extensionsec/xcavate/blob/247f776220f2ed41f64f48174c349b6d7f59d13b/xcavate/data_spider/common.py#L29C1-L31C1

Try to follow this structure for comments:
```python
def get_random_id_from_seed(seed:int) -> str:
    """
    Generates a random extension identifier from a given seed.
    NOTE: a specific seed will always return the same identifier
    """
```

If you want, you can include additional information about the variables and return arguments like this
```python
def get_random_id_from_seed(seed:Optional[int]) -> str:
    """
    Generates a random extension identifier from a given seed.

    Args:
        seed: makes the function generate a fixed identifier; if unset, the generated identifiers will change every time that the function is called.

    Returns:
        A randomly-generated valid extension identifier
    """
```

When documenting your functions and classes try to follow this standard (it will help others to read your code, but most importantly, it will be helpful for you as well when you will read this code in the future).

**Comment by valbucci** [comment]
https://github.com/extensionsec/xcavate/blob/247f776220f2ed41f64f48174c349b6d7f59d13b/xcavate/data_spider/common.py#L1-L6

Can you remove these parts from your code? If you want, and I recommend it, add to the first line of your modules a description of what the module does, formatted like this:

```python
"""This file mainly contains the implementation of some annotations, such as requesting ten times to prevent data loss, etc."""
```

However, I would change the description with something more meaningful such as:
```python
"""Provides functionalities for the SpiderCrawler class"""
```

**Comment by Yang-Nankai** [comment]
https://github.com/extensionsec/xcavate/blob/29b4c68ec0f72fb3f345c0063a3d7becfb260271/xcavate/data_management/crx_archive.py#L479

In this line, I changed the code into `js_code.encode('utf-8')`, or it will display `TypeError: Strings must be encoded before hashing`.
@valbucci
